### ISSUE TITLE
Enhancement: Fullscreen auto-resize

### ISSUE THREAD

**Issue by ethanaobrien** [copy/v86#642]
It would be nice when the virtual machine is fullscreened if the scale automatically adjusted to make it as big as it can. Sorry If this is hard to understand

**Comment by WRA1TH-n-vengence** [comment]
Nah that makes perfect sense, an although that sounds easy, there's a reason most sites or hardware have an adjustable ratio instead. You are talking cross-device aspect ratio resizing, right?
anyways, sounds plausible, you'd need an identification method to see the ratio, and some simple methods to convert it.
Idk though, I'm just an over-analyzer.
all in all, whomever figures it out, please @ me, this seems great

**Comment by kyr0** [comment]
Assuming you're talking about `canvas` aka VGA mode and assuming that the element that contains the `canvas` has the CSS class `fullscreen` set, when you're entering fullscreen mode, you can add the following CSS selector overrides to your code to get response, aspect-ratio-respecting auto-resize on fullscreen:

```css

.fullscreen {
  display: flex;
}

.fullscreen canvas {
  margin-top: auto;
  width: 100vw !important;
  height: auto !important;
  margin-bottom: auto;
}
```
